### ISSUE TITLE
Elementary Tor adversary

### ISSUE THREAD

**Issue by seresistvanandras** [ferencberes/ethp2psim#30]
Create an adversary that is randomly distributed in the graph and always wins if it has at least 2 nodes on an arm of a TOR tunnel. In the other cases, it cannot say anything about the message originator.

**Comment by ferencberes** [comment]
The first version of OnionRoutingAdversary was implemented. Remaining tasks:
- [ ] Finish debugging
- [ ] Write a few more tests
- [ ] Support multi-armed OnionRoutingProtocol
